官方已弃用 Variable
beeth0ven/RxSwift-Chinese-Documentation pull request #44
Opened 2020-09-10 08:03 UTC by professordeng

2020-09-10 13:21 UTC, beeth0ven requested changes

2020-09-10 13:21 UTC, beeth0ven commented on content/decision_tree/flatMap.md
> +let variable = BehaviorSubject(value: first)
Also, It's better to rename `let variable` to `let subject`.

2020-09-10 13:21 UTC, beeth0ven commented on content/decision_tree/flatMap.md
> +variable.onNext(second)
Same here.

2020-09-10 13:46 UTC, professordeng reviewed
谢谢指正，已修改～

2020-09-13 05:32 UTC, merged

2020-09-13 05:32 UTC, beeth0ven commented
Thank you!